coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 85%
        threshold: 2%
ignore:
  - 'tests/*'
  - 'examples/*'
  - 'doc/*'
  - 'setup.py'
