[tool.poetry]
name = "dnspython"
version = "2.0.0"
description = "DNS toolkit"
authors = ["Bob Halley <halley@dnspython.org>"]
license = "ISC"
packages = [
    {include = "dns"}
]

[tool.poetry.dependencies]
python = "^3.6"
requests-toolbelt = {version="^0.9.1", optional=true}
requests = {version="^2.23.0", optional=true}
idna = {version="^2.1", optional=true}
cryptography = {version="^2.6", optional=true}
trio = {version="^0.14.0", optional=true}

[tool.poetry.dev-dependencies]
mypy = "^0.770"
pytest = "^5.4.1"
flake8 = "^3.7.9"
sphinx = "^3.0.0"
coverage = "^5.1"

[tool.poetry.extras]
doh = ['requests', 'requests-toolbelt']
idna = ['idna']
dnssec = ['cryptography']
trio = ['trio']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
