[tool.poetry]
name = "dnspython"
version = "2.2.0"
description = "DNS toolkit"
authors = ["Bob Halley <halley@dnspython.org>"]
license = "ISC"
packages = [
    {include = "dns"}
]

[tool.poetry.dependencies]
python = "^3.6"
requests-toolbelt = {version="^0.9.1", optional=true}
requests = {version="^2.23.0", optional=true}
idna = {version=">=2.1,<4.0", optional=true}
cryptography = {version=">=2.6,<4.0", optional=true}
trio = {version=">=0.14,<0.20", optional=true}
curio = {version="^1.2", optional=true}
sniffio = {version="^1.1", optional=true}

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = ">=5.4.1,<7"
pytest-cov = "^2.10.0"
flake8 = "^3.7.9"
sphinx = "^4.0.0"
coverage = "^5.1"
twine = "^3.1.1"
wheel = "^0.35.0"
pylint = "^2.7.4"

[tool.poetry.extras]
doh = ['requests', 'requests-toolbelt']
idna = ['idna']
dnssec = ['cryptography']
trio = ['trio']
curio = ['curio', 'sniffio']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]